name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - run: echo "Hello, world!"
      - run: echo "correr tests"
      - run: echo "ejecutar sonar" 
      - run: echo "publicar version"